[package]
description = "A simple STUN client library and command line tool"
license = "LICENSE"
name = "stun"
version = "0.0.1"
authors = ["Zac Stewart <zgstewart@gmail.com>"]

[lib]
name = "stun"
path = "src/lib.rs"

[[bin]]
name = "stun"
path = "src/main.rs"

[dependencies]
